services:
  redis:
    image: redis/redis-stack-server:latest
    ports: 
      - 6379:6379
  app:
    build:
      context: .
    environment:
      REDIS_URL: redis://redis:6379
      APP_PORT: 8000
    ports:
      - 8000:8000
    depends_on:
     - redis